version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ujimysqlkudb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3309:3306'

volumes:
  mysql_data:
